[general]
import = [
	"themes/zenwritten_light.toml"
]

[window]
startup_mode = "Fullscreen"
dynamic_padding = true

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
# brewmaster: 17 | JAAM: 14
size = 14

[mouse]
hide_when_typing = true

# vim: foldmethod=marker foldlevel=0
