[general]
import = [
	"themes/kanagawa_lotus.toml"
	# "themes/kanagawa_wave.toml"
]

[window]
startup_mode = "Fullscreen"
dynamic_padding = true

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
# brewmaster: 17 | JAAM: 14
size = 14

[mouse]
hide_when_typing = true
