# file taken from https://github.com/zenbones-theme/zenbones.nvim
# with modifications to match zenwritten's dim variant

# these 16 colours match exactly with colors/zenwritten.vim
[colors.normal]
black = "#EEEEEE"
red = "#A8334C"
green = "#4F6C31"
yellow = "#944927"
blue = "#286486"
magenta = "#88507D"
cyan = "#3B8992"
white = "#353535"

[colors.bright]
black = "#C6C3C3"
red = "#94253E"
green = "#3F5A22"
yellow = "#803D1C"
blue = "#1D5573"
magenta = "#7B3B70"
cyan = "#2B747C"
white = "#5C5C5C"

# GIMP says the dim bg is #E5E5E5, but specs from the repo says
# its #EEEEEE.abs_darken(3) -> #E6E6E6...
# i'll trust GIMP on this one.

[colors.cursor]
cursor = "#353535"
text = "#E5E5E5"

[colors.primary]
background = "#E5E5E5"
foreground = "#353535"
